### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-oauth#2]
# Documentations
- [x] Document how to use oauths

_Needs more investigation!_

# Oauths
The following OAuths are working or have been submitted to be implemented into HumHub

### Under Development
- [ ] [Slack](/GreenMeteor/humhub-oauth/tree/master/oauth/Slack)
- [x] [RocketFirm](/GreenMeteor/humhub-oauth/tree/master/oauth/Rocket%20Firm)
- [ ] [HumHub](/GreenMeteor/humhub-oauth/blob/master/oauth/HumHub)

### Needs Tested
- [ ] [Foursquare](/GreenMeteor/humhub-oauth/tree/master/oauth/Foursquare)
- [ ] [WeChat](/GreenMeteor/humhub-oauth/tree/master/oauth/WeChat)
- [x] ~[Odnoklassniki](/GreenMeteor/humhub-oauth/tree/master/oauth/Odnoklassniki)~
- [ ] [QQ](/GreenMeteor/humhub-oauth/tree/master/oauth/QQ)
- [ ] [Lianluo](/GreenMeteor/humhub-oauth/tree/master/oauth/Lianluo)
- [ ] [Storenvy](/GreenMeteor/humhub-oauth/tree/master/oauth/Storenvy)
- [ ] [Apple](/GreenMeteor/humhub-oauth/tree/master/oauth/Apple)

### Tested
- [x] [Discord](/GreenMeteor/humhub-oauth/tree/master/oauth/Discord)
- [x] [Patreon](/GreenMeteor/humhub-oauth/tree/master/oauth/Patreon) (#5)
- [x] ~[Pinterest](/GreenMeteor/humhub-oauth/tree/master/oauth/Pinterest) (#4 )~
- [ ] [Tumblr](/GreenMeteor/humhub-oauth/tree/master/oauth/Tumblr)
- [x] [Twitch](/GreenMeteor/humhub-oauth/tree/master/oauth/Twitch)
- [x] [Mastodon](/GreenMeteor/humhub-oauth/tree/master/oauth/Mastodon)

### Deprecated Oauths
- [x] Instagram (Now officially deprecated!)
- [x] Soundcloud (Now officially deprecated!)
- [x] Pinterest (Officially deprecated)
- [x] Odnoklassniki (Officially deprecated)

### Submitted
- [x] [LinkedIn](/humhub/humhub/blob/master/protected/humhub/modules/user/authclient/LinkedIn.php)
- [x] Twitter (Is in v1.3 release!)
- [x] ~[Instagram](/GreenMeteor/humhub-oauth/tree/master/oauth/Instagram) (Now deprecated!)~

**Comment by Buliwyfa** [comment]
what about live and wordpress?

**Comment by Felli** [comment]
@Buliwyfa the WordPress oauth has some malformed url issues at this time, so I didn't add it to the list.

**Comment by Felli** [comment]
As for Live, this was a default on install if I'm right, and this should work by default am I wrong?

**Comment by Felli** [comment]
Updated with Twitch Oauth being added to tested oauths.

**Comment by Felli** [comment]
The [SoundCloud oauth](https://github.com/GreenMeteor/humhub-oauth/blob/master/oauth/Soundcloud/Soundcloud.php) is now up on the chopping block and will be discussed if we should deprecate it because they closed [registering new apps](https://developers.soundcloud.com/) and it doesn't look like they will be opening it up any time soon.

**Comment by nenoken** [comment]
Hello @Felli , it is may be possible to make a wordpress client compatible?... with this plugin https://wordpress.org/plugins/oauth2-provider/ (wordpress self-hosted)

**Comment by Felli** [comment]
@nenoken we'd rather stay on point and go through WordPress rather than force users to use multiple 3rd party sources.

**Comment by ArchBlood** [comment]
Added Apple OAuth2 login to ***Needed Tested***
